version: '3.8'

#volumes:
#  vol:
#    external: true
#    name: vol

services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3308
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: memberpj
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    expose:
      - 3308

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/memberpj?useSSl=false
    ports:
      - "8080:8080"
    depends_on:
      - mysql