spring:
  application:
    name: memberpj
  datasource:
    url: jdbc:postgresql://localhost:5432/memberpj
    driver-class-name: org.postgresql.Driver
    username: member_admin
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: create
#        Application 실행시 DB 초기화
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
    defer-datasource-initialization: true
    profiles:
      include: create
  logging:
    level:
      org.hibernate.SQL: debug
      org.springframework.jdbc: debug

jwt:
  key: dajishflkajhdflkajhzsdfljkhadsflkjh123!!DF
  access-token-expiration-minutes: 999999
  refresh-token-expiration-minutes: 999999