spring:
  application:
    name: memberpj
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PW}
  jpa:
    hibernate:
      ddl-auto: create
#        Application 실행시 DB 초기화
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true
    defer-datasource-initialization: true
    profiles:
      include: create
  logging:
    level:
      org.hibernate.SQL: debug
      org.springframework.jdbc: debug

jwt:
  key: user-springboot
  access-token-expiration-minutes: 999999
  refresh-token-expiration-minutes: 999999